Fix TypeError: 'Namespace' object does not support item assignment
Full error:

    Traceback (most recent call last):
      File "/home/mg/.local/bin/gitlab-jobs", line 11, in <module>
        load_entry_point('gitlab-jobs', 'console_scripts', 'gitlab-jobs')()
      File "/home/mg/src/gitlab-jobs/gitlab_jobs.py", line 136, in main
        for job in get_jobs(pipeline, args):
      File "/home/mg/src/gitlab-jobs/gitlab_jobs.py", line 45, in get_jobs
        args['scope'] = 'success'
    TypeError: 'Namespace' object does not support item assignment